### ISSUE TITLE
Customizable pronouns for each character.

### ISSUE THREAD

**Issue by 12beesinatrenchcoat** [12beesinatrenchcoat/incorrect-quotes-generator#2]
What it says on the tin, each character should be allowed to have their own set of pronouns (defaults to they/them/themselves).

Still trying to figure out how I'd do this, though.

## Todo list of implementation
- [x] #4
- [x] Dynamic defaults (as in, type something like "him" for object pronoun, have the reflexive autofill "himself".)
	- [x] Treat as singular / plural?
		- He/she/xe **is**, they **are**, etc.
		- Also has a potential issue with verbs. Oh boy.
		- See also: #3 
- [x] #7
	- [x] Proper dropdowns
	  - Kinda done in https://github.com/AndyThePie/incorrect-quotes-generator/commit/29422fafdb70f8dcc72a993780d2d901aff18cd9, I guess
	- [ ] Better explanation of what each pronoun is.
	  - Scrapped the whole "oh yes this is the Object Pronoun" thing, but might also make a separate page/note for it because I admit it can be kind of vague.
